// UI text for the session view, in the language the lesson is being taught
// in. Scope is deliberate: the screen where a German conversation is
// happening should not be captioned in English. The recap's own content
// already comes back translated from the grader.
//
// Placeholders are {name}, {them}, {topic} — filled by t().

const STRINGS = {
  en: {
    ready: "{name} is ready. Press the microphone and start teaching {them} about {topic}.",
    pressMic: "Press the microphone and start explaining.",
    connecting: "Connecting to {name}...",
    speaking: "🔊 {name} is speaking...",
    listening: "🎙️ {name} is listening...",
    thinking: "💭 {name} is thinking...",
    startTeaching: "🎙️ Start teaching {name}...",
    muted: "🔇 Microphone muted — {name} can't hear you.",
    restingHint: "🤔 Take your time — {name} is waiting quietly.",
    isSpeaking: "{name} is speaking",
    isListening: "{name} is listening",
    isThinking: "{name} is thinking",
    waiting: "waiting for you",
    yourLesson: "YOUR LESSON",
    pointsMentioned: "POINTS MENTIONED",
    waitingForSignal: "WAITING FOR SIGNAL",
    challenge: "CHALLENGE {them}",
    commonWrong: "WHAT BEGINNERS USUALLY GET WRONG",
    dontSay: "DON'T SAY",
    jargonTitle: "WORDS YOU'RE USING",
    jargonEmpty: "Nothing technical yet. Terms appear here as you say them.",
    jargon_used: "said",
    jargon_queried: "{they} stopped you",
    jargon_cleared: "explained",
    jargonStopped: "{count} of these stopped {them}. Those are the ones to say another way.",
    jargonSoFar: "Nothing has tripped {them} up yet.",
    micUnmute: "Unmute your microphone",
    micMute: "Mute your microphone",
    pauseHint: "Take a moment. {name} waits, and won't ask if you're still there",
    resumeHint: "Carry on — {name} starts listening again",
    endCallHint: "End the conversation",
    bannedSlipped: "{count} slipped through — that's fine, keep going.",
    taughtBy: "taught by",
    voiceOnly: "🎙️ Voice only",
    showPanels: "🗒️ Show the panels",
    letMeThink: "🤔 Let me think",
    imReady: "▶︎ I'm ready",
    endCall: "⏹️ End conversation",
    askUnderstood: "{glyph} Ask {name} what {they} understood",
    asked: "{glyph} Asked — listen to what {they} got",
    recallHint: "{name} will say back what {they} thinks {they} understood",
    finish: "Finish lesson →",
    seeNotes: "See {name}'s Notes →",
    teachSomethingElse: "← Teach something else",
    justTalk: "Just talk. {name} will tell you what {they} understood at the end.",
    coveredAll: "You covered all four points.",
    confidenceQ: "Before you start — how well do you think you know {topic}?",
    confShaky: "Shaky",
    confOk: "Pretty well",
    confStrong: "I could teach it",
    conceptDensity: "Concept density",
    prerequisites: "Prerequisites",
    Beginner: "Beginner",
    Intermediate: "Intermediate",
    Advanced: "Advanced",
    butDid: "But did {name} actually follow it? Finish the lesson and {they}'ll tell you.",

    // Landing page. The product name itself stays English — it is the
    // brand, not a sentence.
    heroLine1: "If you can't explain it",
    heroLine2: "to {name},",
    heroLine3: "do you really understand it?",
    heroSub: "Name anything you know. Then try to teach it to someone who knows absolutely nothing about it.",
    createCharacter: "Create your character",
    editCharacter: "Edit your character",
    whoTeaching: "Who are you teaching?",
    whatTeach: "What do you want to teach?",
    teachIn: "Teach in",
    topicPlaceholder: "Backpropagation, embeddings, why transformers replaced RNNs…",
    teachIt: "Teach it →",
    preparing: "Preparing…",
    workingOut: "Working out what {name} would need to hear…",
    gotCode: "Got a Teach-Off code?",
    takePhoto: "📷 Take a photo",
    usePhoto: "Choose a file",
    photoCapture: "Capture",
    photoCancel: "Cancel",
    cameraBlocked: "Camera blocked — allow it via the padlock in the address bar.",
    cameraMissing: "No camera found. Choose a file instead.",
    photoReading: "Matching your photo…",
    photoMatched: "Matched from your photo — adjust anything below.",
    photoFailed: "Couldn't read that photo. Set the dials yourself.",
    photoPrivacy: "Sent once to pick the dials. Never stored.",
    yourName: "Your name",
    join: "Join →",
    orTry: "Or try",
    clearLesson: "Clear saved lesson",
    resetAll: "Reset everything",
    presetHint: "Start from this one, then tweak",
    clearLessonHint: "Clears any half-finished lesson still saved in this tab. Keeps your name, XP and badges.",
    resetAllHint: "Deletes your name, face, XP and badges as well",
    resetAllConfirm: "Clear everything?\n\nYour name, face, XP and badges will be deleted. This can't be undone.",
    dropped: "{name} hung up. Press the microphone to carry on — nothing you said is lost.",
    you: "YOU",
    // Recap
    // The caller passes an already-uppercased name; uppercasing the
    // template here instead would break the {name} placeholder itself.
    notesOf: "{name}'S NOTES",
    recapSub: "Here's what {name} understood from your lesson on",
    feynmanScore: "FEYNMAN SCORE",
    says: "{name} SAYS",
    marking: "{name} is marking your lesson…",
    reallyUnderstand: "Did {name} really understand?",
    predictTitle: "What it expected you to struggle with",
    predictIntro: "Predicted before you said a word, from the topic alone.",
    asPredicted: "as predicted",
    caughtYouOut: "caught you out",
    youBeatIt: "you beat it",
    expectedYouGot: "expected {level} · you got it across",
    expectedYouDidnt: "expected {level} · you did not",
    depthTitle: "How deep you went",
    youGotHere: "you got here",
    nextRung: "Next rung:",
    blindTitle: "What you never went near",
    blindIntro: "Not explained badly — never mentioned at all.",
    juryTitle: "The jury",
    juryOwnScale: "Each juror scores on their own standard. This is not the Feynman Score above — that one is computed, these are judged.",
    juryDeliberating: "The jury is deliberating…",
    jurySpreadWide: "{spread} points between {kindest} and {toughest}. It worked for one of them and not the other — that gap is the thing worth fixing.",
    jurySpreadTight: "Only {spread} points apart. It landed about the same for all four, which is the hard part.",
    workingOutTookAway: "{name} is working out what {they} actually took away…",
    juryIntro: "Four listeners, four standards. The same explanation can land for one and fail for another.",
    convene: "Convene the jury →",
    explainBackTitle: "Let me see if I understood you",
    recallAsk:
      "{name}, before I go — can you tell me back what you understood, in your own words?",
    youCovered: "You covered",
    theyFollowed: "{name} followed",
    couldRepeat: "{they} could repeat back",
    gapLadder:
      "Each step is a harder test than the one before it. Repeating your words back is not the same as following them.",
    tookAway: "What {name} took away",
    saidOutLoud: "What {name} said out loud",
    undefinedWords: "Words you used but never explained",
    fromYourOwn: "Every word above came from your own explanation.",
    strongest: "Your strongest moment",
    theyFollowedTitle: "What {name} followed",
    toImprove: "What to improve",
    neededHelp: "Where {name} needed help",
    yourExplanation: "Your explanation",
    turnedTitle: "Where it turned",
    turnedIntro: "The moments that decided this lesson, in the order they happened.",
    deliveryTitle: "How you said it",
    mirrorTitle: "Now check {theirs} work",
    mirrorIntro: "{name} retells your lesson — with a couple of things deliberately wrong. Catch them.",
    mirrorStart: "🪞 Let's hear it →",
    teachoffTitle: "Think someone can beat that?",
    teachoffIntro: "They teach the exact same lesson, {name} grades them the same way, one board settles it.",
    startTeachoff: "⚔️ Start a Teach-Off",
    runTitle: "The run",
    taughtTo: "taught to {name}",
    scoreLabel: "Feynman score",
    pointsFollowed: "points followed",
    onTheMic: "on the mic",
    xpEarned: "XP earned",
    copySummary: "Copy summary",
    takeChallenge: "🎯 Take the challenge →",
    predictedLabel: "You predicted",
    measuredLabel: "Measured",
    trapTitle: "The trap {name} set",
    thisTeachoff: "This Teach-Off",
    verdictGot: "{name} really got it.",
    verdictMostly: "{name} mostly followed you.",
    verdictSome: "{name} got some of it.",
    verdictLost: "{name} is still lost.",
    verdictLostGrandma: "Grandma is still lost, darling.",
    xpCompleted: "Completed the lesson",
    xpEveryConcept: "Mentioned every concept",
    xpExplainedOne: "Explained 1 point clearly",
    xpExplainedMany: "Explained {count} points clearly",
    xpUnderstoodAll: "{name} understood all of it",
    xpJargon: "Dropped the jargon when asked",
    xpSelfCorrect: "Caught your own mistake",
    xpAnalogy: "Found a good analogy",
    achJargonSlayer: "Jargon Slayer",
    achJargonSlayerHow: "Swap a technical term for plain language when asked",
    achApproved: "Fully Followed",
    achApprovedHow: "Every point understood, at most one interruption",
    achDeepThinker: "Deep Thinker",
    achDeepThinkerHow: "Give five of their questions a real answer",
    achPerfect: "Perfect Explanation",
    achPerfectHow: "Score 95 or higher",
    achSpeed: "Speed Teacher",
    achSpeedHow: "Every point understood in under three minutes",
    achMythBuster: "Myth Buster",
    achMythBusterHow: "Catch them confidently stating a false belief",
    achAnalogyMaster: "Analogy Master",
    achAnalogyMasterHow: "A genuine analogy in three different lessons",
    achFeynmanMaster: "Feynman Master",
    achFeynmanMasterHow: "Ten lessons scoring 75 or higher",
    dlPace: "Pace",
    dlPaceUnit: "words per minute",
    dlPaceFast: "Quick. A beginner needs longer to catch up than a peer does.",
    dlPaceSlow: "Unhurried — which suits a listener meeting this for the first time.",
    dlPaceSteady: "A steady conversational pace.",
    dlFillers: "Filler words",
    dlFillersTop: "most often \"{term}\"",
    dlNoneCounted: "none counted",
    dlFillersHigh: "{rate} per 100 words — enough that they carry into the explanation.",
    dlFillersOk: "Within the range of ordinary spoken explanation.",
    dlHedges: "Hedging",
    dlHedgesHigh: "Softened claims give a beginner less to hold onto than a plain statement does.",
    dlHedgesOk: "Claims were mostly stated plainly.",
    dlSentences: "Sentence length",
    dlSentencesUnit: "words on average",
    dlSentencesLong: "Long sentences ask a listener to hold several ideas at once.",
    dlSentencesOk: "Short enough to follow one idea at a time.",
    levelEasy: "easy",
    levelTricky: "tricky",
    levelHard: "hard",
    replayCode: "Teach-Off",
    tpLanded: "Landed",
    tpLost: "Lost {them}",
    tpRecovered: "Recovered",
    tpJargon: "Jargon",
    rungNamed: "Named it",
    rungNamedHint: "You said what it is called",
    rungDefined: "Defined it",
    rungDefinedHint: "A correct definition — the kind you can memorise",
    rungMechanism: "Explained how",
    rungMechanismHint: "Why one step leads to the next",
    rungApplied: "Showed it working",
    rungAppliedHint: "A concrete case, worked through",
    rungBoundaries: "Knew its limits",
    rungBoundariesHint: "When it fails or does not apply",
    copyTaughtTo: "{topic} — taught to {name}",
    copyScore: "Feynman score: {score}/100",
    copyPoints: "Points followed: {count}/{total}",
    copyTime: "Time on the mic: {duration}",
    copyBestLine: "Best line: \"{quote}\"",
    copyCode: "Teach-Off code: {code}",
    mirrorCaughtN: "You caught {caught} of {total}",
    mirrorNoFalse: " — and didn't flag anything that was fine.",
    mirrorSomeFalse: " — but flagged {count} that were actually fine.",
    noMark: "{name} couldn't mark this one — XP for coverage only.",
    confidentBy: "You were {gap} points more confident than the explanation turned out to be.",
    soldShort: "You sold yourself short by {gap} points.",
    knewWhere: "You knew roughly where you stood.",
    xpRunning: "{xp} XP total in this browser",
    thinkingOver: "{name} is thinking it over…",
    midLessonClaimed: "Mid-lesson, {name} claimed:",
    youCaughtIt: "✓ You caught it",
    walkedAway: "○ {name} walked away still believing it. That false idea went unchallenged.",
    nothingClear: "Nothing came across clearly yet.",
    followedEvery: "{name} followed every point. That's the whole idea.",
    noQuestions: "{name} didn't have any major questions about your explanation.",
    noExplanation: "You didn't give {name} an explanation yet.",
    juryTap: "Tap a juror to hear what they made of it.",
    deliveryIntro: "Counted from your own words — {words} of them{over}. This is about delivery, not whether you were right.",
    deliveryOver: " over {duration}",
    mirrorGetting: "Getting the story straight…",
    mirrorHowYouDid: "Here's how you did:",
    mirrorFlagAll: "Flag every claim you think is wrong, then lock it in. ({count} of them are.)",
    mirrorThatsWrong: "⚑ that's wrong",
    mirrorCaught: "✓ caught it",
    mirrorMissed: "✗ this one was wrong — you let it through",
    mirrorFine: "○ this one was actually fine",
    mirrorLockIn: "Lock it in →",
    teachoffNext: "Next teacher joins with code {code} on the start page — same lesson, same judge.",
    teachoffFirst: "You're first on the board. Hand someone the mic.",
    boardUnderstood: "{count}/{total} understood",


    // Character builder
    yourCharacter: "Your character",
    hair: "Hair",
    facialHair: "Facial hair",
    glasses: "Glasses",
    expression: "Expression",
    skin: "Skin",
    backdrop: "Backdrop",
    thatsMe: "That's me →",
    saving: "Saving…",

    // The quiz side mode. Its own vocabulary, because it is deliberately a
    // different measurement from everything above — and the strings say so
    // out loud rather than leaving someone to conclude the app thinks a
    // score out of fifteen is understanding.
    quizEntryLabel: "Side mode",
    quizEntryButton: "Two-player quiz →",
    quizEntryNote: "Recall against a clock — a different measurement.",
    quizSideMode: "SIDE MODE",
    quizTitle: "The quiz game",
    quizWhatItIs:
      "Two players, fifteen questions, one clock. This measures whether you can pick the right answer fast — which is not the same thing as being able to explain it, and is why it sits beside the lesson rather than in front of it.",
    quizScoring: "+100 right · −50 wrong · answers at the end, not between",
    quizTopicLabel: "What's the quiz about?",
    quizTopicPlaceholder: "Photosynthesis, the French Revolution, embeddings…",
    quizYourName: "Your name",
    quizCreate: "Make the game →",
    quizJoinLabel: "Or join a game someone else made",
    quizJoin: "Join",
    quizBack: "← Back",
    quizBuilding: "Writing fifteen questions…",
    quizVoicing: "Recording question {done} of {total}…",
    quizYourCode: "YOUR CODE",
    quizShareCode:
      "Read this out. The other player types it in on their own device.",
    quizPlayers: "PLAYERS",
    quizWaiting: "Waiting for the second player…",
    quizStart: "Start the game →",
    quizStarting: "Starting…",
    quizWaitingHost: "Waiting for {name} to start the game…",
    quizHostIs: "made the game",
    quizYouAre: "you",
    quizSilent:
      "No voice on this one — the questions will be on screen only.",
    quizCountdown: "Get ready…",
    quizQuestionOf: "QUESTION {n} OF {total}",
    quizListen: "🔊 Listen…",
    quizLockedIn: "Locked in",
    quizTheyAnswered: "{name} has answered",
    quizWaitingThem: "Waiting for {name}…",
    quizNoAnswerYet: "No answer from you",
    quizOver: "That's fifteen.",
    quizWinner: "{name} wins",
    quizDraw: "A draw",
    quizRight: "right",
    quizWrong: "wrong",
    quizMissed: "no answer",
    quizAnswers: "THE ANSWERS",
    quizTrickyBadge: "TRAP",
    quizCorrectLabel: "Correct",
    quizNobody: "nobody",
    quizPlayAgain: "New game",
    quizLeave: "← Back to teaching",
    quizLeaveGame: "← Leave this game",

    // The display-mode switch. The label names the mode you are IN; the
    // tooltip names the one you would get.
    themeLight: "Light",
    themeDark: "Dark",
    themeToLight: "Switch to light mode",
    themeToDark: "Switch to dark mode",

    // The wait after a topic is named. These are the real steps the server
    // takes, in order, so the pause reads as work rather than as lag.
    thinkingStep1: "Reading your topic…",
    thinkingStep2: "Working out what it really involves…",
    thinkingStep3: "Deciding what {name} would struggle with…",
    thinkingStep4: "Writing the four points you'll need to cover…",

    // The arrival. Two beats: the provocation, then who is waiting.
    // Written to be read in about four seconds and to make someone slightly
    // uncomfortable, because that discomfort IS the product's argument.
    introEyebrow: "TEACH IT TO GRANDMA",
    introLine1: "You think",
    introLine2: "you know it.",
    introBody: "You've read it. You've nodded along. You could probably pass the test.",
    introEnter: "Prove it →",
    introSkip: "Skip",
    intro2Line1: "Now say it to someone",
    intro2Line2: "who knows nothing.",
    intro2Body: "Grandma is 78. She has never heard of your subject. She asks \"why?\" until you run out of answers.",
    intro2Enter: "I'm ready →",
    introHint: "Press Enter",

    // Shown when the deploy's own key has expired and a visitor can carry on
    // with their own.
    keyTitle: "This demo needs an API key",
    keyBody: "The key this demo shipped with is no longer active. If you have a TitanomGPT key, paste it below and everything works again — lessons, grading and the quiz.",
    keyPlaceholder: "sk_…",
    keySave: "Use this key",
    keySaved: "Saved — try again",
    keyForget: "Forget it",
    keyPrivacy: "Kept in this browser tab only, sent with your requests, and never stored on the server. Closing the tab forgets it.",
    quizRecallNote:
      "Fifteen right answers is a good memory. Whether you could explain any one of them out loud is a different question — and that one is upstairs.",
    quizNoGame: "No game with that code.",
    quizGone: "That game has ended.",
    quizFailed: "Could not reach the quiz server. Is it running on port 3001?",
  },

  de: {
    ready: "{name} ist bereit. Drücke das Mikrofon und erkläre {them} {topic}.",
    pressMic: "Drücke das Mikrofon und fang an zu erklären.",
    connecting: "Verbinde mit {name}...",
    speaking: "🔊 {name} spricht...",
    listening: "🎙️ {name} hört zu...",
    thinking: "💭 {name} denkt nach...",
    startTeaching: "🎙️ Fang an, {name} zu unterrichten...",
    muted: "🔇 Mikrofon stumm — {name} kann dich nicht hören.",
    restingHint: "🤔 Lass dir Zeit — {name} wartet ruhig.",
    isSpeaking: "{name} spricht",
    isListening: "{name} hört zu",
    isThinking: "{name} denkt nach",
    waiting: "wartet auf dich",
    yourLesson: "DEINE LEKTION",
    pointsMentioned: "GENANNTE PUNKTE",
    waitingForSignal: "WARTE AUF SIGNAL",
    challenge: "FORDERE {themAcc} HERAUS",
    commonWrong: "WAS ANFÄNGER MEIST FALSCH VERSTEHEN",
    dontSay: "NICHT SAGEN",
    jargonTitle: "WÖRTER, DIE DU BENUTZT",
    jargonEmpty: "Noch nichts Fachliches. Begriffe erscheinen hier, sobald du sie sagst.",
    jargon_used: "gesagt",
    jargon_queried: "hat {they} gestoppt",
    jargon_cleared: "erklärt",
    jargonStopped: "{count} davon haben {themAcc} gestoppt. Die solltest du anders sagen.",
    jargonSoFar: "Bisher ist {they} über nichts gestolpert.",
    micUnmute: "Mikrofon wieder anschalten",
    micMute: "Mikrofon stummschalten",
    pauseHint: "Lass dir Zeit. {name} wartet und fragt nicht nach, ob du noch da bist",
    resumeHint: "Weiter — {name} hört wieder zu",
    endCallHint: "Das Gespräch beenden",
    bannedSlipped: "{count} durchgerutscht — kein Problem, mach weiter.",
    taughtBy: "unterrichtet von",
    voiceOnly: "🎙️ Nur Stimme",
    showPanels: "🗒️ Panels zeigen",
    letMeThink: "🤔 Lass mich überlegen",
    imReady: "▶︎ Ich bin bereit",
    endCall: "⏹️ Gespräch beenden",
    askUnderstood: "{glyph} Frag {name}, was {they} verstanden hat",
    asked: "{glyph} Gefragt — hör zu, was {they} verstanden hat",
    recallHint: "{name} sagt dir, was {they} verstanden zu haben glaubt",
    finish: "Lektion beenden →",
    seeNotes: "Notizen von {name} ansehen →",
    teachSomethingElse: "← Etwas anderes erklären",
    justTalk: "Sprich einfach. {name} sagt dir am Ende, was {they} verstanden hat.",
    coveredAll: "Du hast alle vier Punkte angesprochen.",
    confidenceQ: "Bevor du anfängst — wie gut kennst du {topic} deiner Meinung nach?",
    confShaky: "Wackelig",
    confOk: "Ganz gut",
    confStrong: "Ich könnte es unterrichten",
    conceptDensity: "Konzeptdichte",
    prerequisites: "Vorkenntnisse",
    Beginner: "Anfänger",
    Intermediate: "Mittelschwer",
    Advanced: "Fortgeschritten",
    butDid: "Aber hat {name} es wirklich verstanden? Beende die Lektion und du erfährst es.",

    heroLine1: "Wenn du es",
    heroLine2: "{name} nicht erklären kannst,",
    heroLine3: "verstehst du es dann wirklich?",
    heroSub: "Nenne etwas, das du kennst. Dann erkläre es jemandem, der absolut nichts darüber weiß.",
    createCharacter: "Erstelle deinen Charakter",
    editCharacter: "Charakter bearbeiten",
    whoTeaching: "Wem erklärst du es?",
    whatTeach: "Was möchtest du erklären?",
    teachIn: "Sprache",
    topicPlaceholder: "Backpropagation, Embeddings, warum Transformer RNNs abgelöst haben…",
    teachIt: "Los geht's →",
    preparing: "Wird vorbereitet…",
    workingOut: "Überlege, was {name} hören müsste…",
    gotCode: "Hast du einen Teach-Off-Code?",
    takePhoto: "📷 Foto aufnehmen",
    usePhoto: "Datei wählen",
    photoCapture: "Aufnehmen",
    photoCancel: "Abbrechen",
    cameraBlocked: "Kamera blockiert — im Schloss-Symbol der Adressleiste erlauben.",
    cameraMissing: "Keine Kamera gefunden. Wähle stattdessen eine Datei.",
    photoReading: "Dein Foto wird abgeglichen…",
    photoMatched: "Aus deinem Foto übernommen — unten kannst du alles anpassen.",
    photoFailed: "Das Foto ließ sich nicht lesen. Stell die Regler selbst ein.",
    photoPrivacy: "Wird einmal gesendet, um die Regler zu wählen. Nie gespeichert.",
    yourName: "Dein Name",
    join: "Beitreten →",
    orTry: "Oder probiere",
    clearLesson: "Gespeicherte Lektion löschen",
    resetAll: "Alles zurücksetzen",
    presetHint: "Hiermit anfangen und dann anpassen",
    clearLessonHint: "Löscht eine angefangene Lektion in diesem Tab. Name, XP und Abzeichen bleiben.",
    resetAllHint: "Löscht auch deinen Namen, dein Gesicht, XP und Abzeichen",
    resetAllConfirm: "Alles löschen?\n\nName, Gesicht, XP und Abzeichen werden gelöscht. Das lässt sich nicht rückgängig machen.",
    dropped: "{name} hat aufgelegt. Drücke das Mikrofon, um weiterzumachen — nichts geht verloren.",
    you: "DU",
    notesOf: "NOTIZEN VON {name}",
    recapSub: "Das hat {name} aus deiner Lektion mitgenommen:",
    feynmanScore: "FEYNMAN-SCORE",
    says: "{name} SAGT",
    marking: "{name} bewertet deine Lektion…",
    reallyUnderstand: "Hat {name} es wirklich verstanden?",
    predictTitle: "Womit du laut Vorhersage Mühe haben würdest",
    predictIntro: "Vorhergesagt, bevor du ein Wort gesagt hast — allein aus dem Thema.",
    asPredicted: "wie vorhergesagt",
    caughtYouOut: "hat dich erwischt",
    youBeatIt: "du warst besser",
    expectedYouGot: "erwartet: {level} · du hast es rübergebracht",
    expectedYouDidnt: "erwartet: {level} · hast du nicht",
    depthTitle: "Wie tief du gegangen bist",
    youGotHere: "bis hierher",
    nextRung: "Nächste Stufe:",
    blindTitle: "Was du gar nicht angesprochen hast",
    blindIntro: "Nicht schlecht erklärt — überhaupt nicht erwähnt.",
    juryTitle: "Die Jury",
    juryOwnScale: "Jeder Juror bewertet nach eigenem Maßstab. Das ist nicht der Feynman-Score oben — der wird berechnet, diese hier werden beurteilt.",
    juryDeliberating: "Die Jury berät…",
    jurySpreadWide: "{spread} Punkte zwischen {kindest} und {toughest}. Bei einem hat es funktioniert, beim anderen nicht — diese Lücke lohnt sich zu schließen.",
    jurySpreadTight: "Nur {spread} Punkte auseinander. Es kam bei allen vier ähnlich an, und genau das ist der schwierige Teil.",
    workingOutTookAway: "{name} überlegt gerade, was {they} wirklich mitgenommen hat…",
    juryIntro: "Vier Zuhörer, vier Maßstäbe. Dieselbe Erklärung kann bei einem ankommen und beim anderen scheitern.",
    convene: "Jury einberufen →",
    explainBackTitle: "Mal sehen, ob ich dich verstanden habe",
    recallAsk:
      "{name}, bevor ich gehe — kannst du mir in deinen eigenen Worten sagen, was du verstanden hast?",
    youCovered: "Du hast angesprochen",
    theyFollowed: "{name} ist gefolgt",
    couldRepeat: "{they} konnte wiedergeben",
    gapLadder:
      "Jede Stufe ist eine härtere Prüfung als die vorige. Deine Worte wiederzugeben heißt nicht, sie verstanden zu haben.",
    tookAway: "Was {name} mitgenommen hat",
    saidOutLoud: "Was {name} laut gesagt hat",
    undefinedWords: "Wörter, die du benutzt, aber nie erklärt hast",
    fromYourOwn: "Jedes Wort oben stammt aus deiner eigenen Erklärung.",
    strongest: "Dein stärkster Moment",
    theyFollowedTitle: "Was {name} verstanden hat",
    toImprove: "Was besser werden kann",
    neededHelp: "Wo {name} Hilfe brauchte",
    yourExplanation: "Deine Erklärung",
    turnedTitle: "Wo es sich entschieden hat",
    turnedIntro: "Die Momente, die diese Lektion entschieden haben, in ihrer Reihenfolge.",
    deliveryTitle: "Wie du es gesagt hast",
    mirrorTitle: "Jetzt prüfe die Version von {name}",
    mirrorIntro: "{name} erzählt deine Lektion nach — mit ein paar absichtlichen Fehlern. Finde sie.",
    mirrorStart: "🪞 Auf geht's →",
    teachoffTitle: "Glaubst du, jemand macht es besser?",
    teachoffIntro: "Dieselbe Lektion, dieselbe Bewertung durch {name}, eine Rangliste entscheidet.",
    startTeachoff: "⚔️ Teach-Off starten",
    runTitle: "Der Durchgang",
    taughtTo: "erklärt an {name}",
    scoreLabel: "Feynman-Score",
    pointsFollowed: "Punkte verstanden",
    onTheMic: "am Mikrofon",
    xpEarned: "XP verdient",
    copySummary: "Zusammenfassung kopieren",
    takeChallenge: "🎯 Herausforderung annehmen →",
    predictedLabel: "Deine Einschätzung",
    measuredLabel: "Gemessen",
    trapTitle: "Die Falle von {name}",
    thisTeachoff: "Dieser Teach-Off",
    verdictGot: "{name} hat es wirklich verstanden.",
    verdictMostly: "{name} ist dir größtenteils gefolgt.",
    verdictSome: "{name} hat einen Teil davon verstanden.",
    verdictLost: "{name} ist immer noch verloren.",
    verdictLostGrandma: "Oma versteht immer noch nur Bahnhof, mein Schatz.",
    xpCompleted: "Lektion abgeschlossen",
    xpEveryConcept: "Jedes Konzept angesprochen",
    xpExplainedOne: "1 Punkt klar erklärt",
    xpExplainedMany: "{count} Punkte klar erklärt",
    xpUnderstoodAll: "{name} hat alles verstanden",
    xpJargon: "Fachjargon weggelassen, als du gefragt wurdest",
    xpSelfCorrect: "Eigenen Fehler selbst bemerkt",
    xpAnalogy: "Einen guten Vergleich gefunden",
    achJargonSlayer: "Jargon-Bezwinger",
    achJargonSlayerHow: "Ersetze auf Nachfrage einen Fachbegriff durch einfache Sprache",
    achApproved: "Voll verstanden",
    achApprovedHow: "Jeder Punkt verstanden, höchstens eine Unterbrechung",
    achDeepThinker: "Tiefdenker",
    achDeepThinkerHow: "Gib auf fünf Fragen eine echte Antwort",
    achPerfect: "Perfekte Erklärung",
    achPerfectHow: "Erreiche 95 Punkte oder mehr",
    achSpeed: "Blitzlehrer",
    achSpeedHow: "Jeder Punkt verstanden in unter drei Minuten",
    achMythBuster: "Mythen-Jäger",
    achMythBusterHow: "Ertappe {themAcc} bei einer selbstbewusst falschen Behauptung",
    achAnalogyMaster: "Vergleichsmeister",
    achAnalogyMasterHow: "Ein echter Vergleich in drei verschiedenen Lektionen",
    achFeynmanMaster: "Feynman-Meister",
    achFeynmanMasterHow: "Zehn Lektionen mit 75 Punkten oder mehr",
    dlPace: "Tempo",
    dlPaceUnit: "Wörter pro Minute",
    dlPaceFast: "Schnell. Ein Anfänger braucht länger zum Mitkommen als ein Fachkollege.",
    dlPaceSlow: "Gemächlich — das passt zu jemandem, der das zum ersten Mal hört.",
    dlPaceSteady: "Ein ruhiges Gesprächstempo.",
    dlFillers: "Füllwörter",
    dlFillersTop: "am häufigsten \"{term}\"",
    dlNoneCounted: "keine gezählt",
    dlFillersHigh: "{rate} pro 100 Wörter — genug, dass sie in der Erklärung auffallen.",
    dlFillersOk: "Im Rahmen einer normalen gesprochenen Erklärung.",
    dlHedges: "Abschwächungen",
    dlHedgesHigh: "Abgeschwächte Aussagen geben einem Anfänger weniger Halt als eine klare Feststellung.",
    dlHedgesOk: "Die Aussagen waren überwiegend klar formuliert.",
    dlSentences: "Satzlänge",
    dlSentencesUnit: "Wörter im Schnitt",
    dlSentencesLong: "Lange Sätze verlangen, mehrere Gedanken gleichzeitig zu halten.",
    dlSentencesOk: "Kurz genug, um einem Gedanken nach dem anderen zu folgen.",
    levelEasy: "leicht",
    levelTricky: "knifflig",
    levelHard: "schwer",
    replayCode: "Teach-Off",
    tpLanded: "Angekommen",
    tpLost: "{themAcc} verloren",
    tpRecovered: "Zurückgeholt",
    tpJargon: "Fachjargon",
    rungNamed: "Benannt",
    rungNamedHint: "Du hast gesagt, wie es heißt",
    rungDefined: "Definiert",
    rungDefinedHint: "Eine richtige Definition — die Sorte, die man auswendig lernt",
    rungMechanism: "Erklärt, wie es funktioniert",
    rungMechanismHint: "Warum ein Schritt zum nächsten führt",
    rungApplied: "Gezeigt, wie es wirkt",
    rungAppliedHint: "Ein konkreter Fall, durchgespielt",
    rungBoundaries: "Grenzen gekannt",
    rungBoundariesHint: "Wann es versagt oder nicht gilt",
    copyTaughtTo: "{topic} — erklärt an {name}",
    copyScore: "Feynman-Score: {score}/100",
    copyPoints: "Verstandene Punkte: {count}/{total}",
    copyTime: "Zeit am Mikrofon: {duration}",
    copyBestLine: "Bester Satz: \"{quote}\"",
    copyCode: "Teach-Off-Code: {code}",
    mirrorCaughtN: "Du hast {caught} von {total} gefunden",
    mirrorNoFalse: " — und nichts markiert, was richtig war.",
    mirrorSomeFalse: " — aber {count} markiert, die eigentlich richtig waren.",
    noMark: "{name} konnte das nicht bewerten — XP nur für die Abdeckung.",
    confidentBy: "Du warst {gap} Punkte zuversichtlicher, als die Erklärung am Ende war.",
    soldShort: "Du hast dich um {gap} Punkte unterschätzt.",
    knewWhere: "Du wusstest ungefähr, wo du stehst.",
    xpRunning: "{xp} XP insgesamt in diesem Browser",
    thinkingOver: "{name} überlegt noch…",
    midLessonClaimed: "Mitten in der Lektion behauptete {name}:",
    youCaughtIt: "✓ Du hast es gemerkt",
    walkedAway: "○ {name} glaubt es immer noch. Diese falsche Vorstellung blieb unwidersprochen.",
    nothingClear: "Bisher ist nichts klar rübergekommen.",
    followedEvery: "{name} ist jedem Punkt gefolgt. Genau darum geht es.",
    noQuestions: "{name} hatte keine größeren Fragen zu deiner Erklärung.",
    noExplanation: "Du hast {name} noch nichts erklärt.",
    juryTap: "Tippe auf ein Jurymitglied und höre das Urteil.",
    deliveryIntro: "Aus deinen eigenen Worten gezählt — {words} Wörter{over}. Es geht um die Darbietung, nicht darum, ob du recht hattest.",
    deliveryOver: " in {duration}",
    mirrorGetting: "Die Geschichte wird sortiert…",
    mirrorHowYouDid: "So hast du abgeschnitten:",
    mirrorFlagAll: "Markiere jede Aussage, die du für falsch hältst, und bestätige dann. ({count} davon sind es.)",
    mirrorThatsWrong: "⚑ das ist falsch",
    mirrorCaught: "✓ erwischt",
    mirrorMissed: "✗ diese war falsch — du hast sie durchgelassen",
    mirrorFine: "○ diese war eigentlich richtig",
    mirrorLockIn: "Bestätigen →",
    teachoffNext: "Die nächste Person tritt mit dem Code {code} auf der Startseite bei — gleiche Lektion, gleiche Bewertung.",
    teachoffFirst: "Du bist die erste Person auf der Liste. Gib jemandem das Mikrofon.",
    boardUnderstood: "{count}/{total} verstanden",


    yourCharacter: "Dein Charakter",
    hair: "Haare",
    facialHair: "Bart",
    glasses: "Brille",
    expression: "Gesichtsausdruck",
    skin: "Hautton",
    backdrop: "Hintergrund",
    thatsMe: "Das bin ich →",
    saving: "Wird gespeichert…",

    // Der Quiz-Nebenmodus.
    quizEntryLabel: "Nebenmodus",
    quizEntryButton: "Quiz zu zweit →",
    quizEntryNote: "Abrufen gegen die Uhr — eine andere Messung.",
    quizSideMode: "NEBENMODUS",
    quizTitle: "Das Quizspiel",
    quizWhatItIs:
      "Zwei Spielende, fünfzehn Fragen, eine Uhr. Hier wird gemessen, ob du die richtige Antwort schnell erkennst — und das ist nicht dasselbe, wie sie erklären zu können. Deshalb steht dieser Modus neben der Lektion und nicht vor ihr.",
    quizScoring: "+100 richtig · −50 falsch · Auflösung am Ende, nicht zwischendurch",
    quizTopicLabel: "Worum geht es im Quiz?",
    quizTopicPlaceholder: "Photosynthese, die Französische Revolution, Embeddings…",
    quizYourName: "Dein Name",
    quizCreate: "Spiel erstellen →",
    quizJoinLabel: "Oder tritt einem Spiel bei",
    quizJoin: "Beitreten",
    quizBack: "← Zurück",
    quizBuilding: "Fünfzehn Fragen werden geschrieben…",
    quizVoicing: "Frage {done} von {total} wird aufgenommen…",
    quizYourCode: "DEIN CODE",
    quizShareCode:
      "Lies ihn vor. Die andere Person tippt ihn auf dem eigenen Gerät ein.",
    quizPlayers: "SPIELENDE",
    quizWaiting: "Warte auf die zweite Person…",
    quizStart: "Spiel starten →",
    quizStarting: "Startet…",
    quizWaitingHost: "Warte darauf, dass {name} das Spiel startet…",
    quizHostIs: "hat das Spiel erstellt",
    quizYouAre: "du",
    quizSilent:
      "Diesmal ohne Stimme — die Fragen stehen nur auf dem Bildschirm.",
    quizCountdown: "Gleich geht's los…",
    quizQuestionOf: "FRAGE {n} VON {total}",
    quizListen: "🔊 Hör zu…",
    quizLockedIn: "Antwort steht",
    quizTheyAnswered: "{name} hat geantwortet",
    quizWaitingThem: "Warte auf {name}…",
    quizNoAnswerYet: "Von dir noch keine Antwort",
    quizOver: "Das waren fünfzehn.",
    quizWinner: "{name} gewinnt",
    quizDraw: "Unentschieden",
    quizRight: "richtig",
    quizWrong: "falsch",
    quizMissed: "ohne Antwort",
    quizAnswers: "DIE ANTWORTEN",
    quizTrickyBadge: "FALLE",
    quizCorrectLabel: "Richtig",
    quizNobody: "niemand",
    quizPlayAgain: "Neues Spiel",
    quizLeave: "← Zurück zum Unterrichten",
    quizLeaveGame: "← Dieses Spiel verlassen",

    themeLight: "Hell",
    themeDark: "Dunkel",
    themeToLight: "Zum hellen Modus wechseln",
    themeToDark: "Zum dunklen Modus wechseln",

    thinkingStep1: "Dein Thema wird gelesen…",
    thinkingStep2: "Es wird herausgearbeitet, worum es wirklich geht…",
    thinkingStep3: "Es wird überlegt, womit {name} Schwierigkeiten hätte…",
    thinkingStep4: "Die vier Punkte werden geschrieben, die du abdecken musst…",

    introEyebrow: "ERKLÄR ES DER OMA",
    introLine1: "Du glaubst,",
    introLine2: "du weißt es.",
    introBody: "Du hast es gelesen. Du hast genickt. Die Prüfung würdest du wohl bestehen.",
    introEnter: "Beweise es →",
    introSkip: "Überspringen",
    intro2Line1: "Jetzt erklär es jemandem,",
    intro2Line2: "der nichts davon weiß.",
    intro2Body: "Oma ist 78. Sie hat von deinem Thema noch nie gehört. Sie fragt \"warum?\", bis dir die Antworten ausgehen.",
    intro2Enter: "Ich bin bereit →",
    introHint: "Enter drücken",

    keyTitle: "Diese Demo braucht einen API-Schlüssel",
    keyBody: "Der Schlüssel, mit dem diese Demo ausgeliefert wurde, ist nicht mehr aktiv. Wenn du einen TitanomGPT-Schlüssel hast, füge ihn unten ein — dann funktioniert alles wieder: Lektionen, Bewertung und das Quiz.",
    keyPlaceholder: "sk_…",
    keySave: "Diesen Schlüssel verwenden",
    keySaved: "Gespeichert — versuch es nochmal",
    keyForget: "Verwerfen",
    keyPrivacy: "Wird nur in diesem Browser-Tab gespeichert, mit deinen Anfragen gesendet und nie auf dem Server abgelegt. Beim Schließen des Tabs ist er weg.",
    quizRecallNote:
      "Fünfzehn richtige Antworten sind ein gutes Gedächtnis. Ob du eine davon laut erklären könntest, ist eine andere Frage — und die stellt die Lektion.",
    quizNoGame: "Kein Spiel mit diesem Code.",
    quizGone: "Dieses Spiel ist beendet.",
    quizFailed: "Der Quiz-Server ist nicht erreichbar. Läuft er auf Port 3001?",
  },
};

// German needs the right pronoun case, and it differs from English: the
// object form after "erkläre" is dative, and subject pronouns differ by
// gender. Kept beside the strings so a new character can't forget them.
const PRONOUNS = {
  en: {
    she: { they: "she", them: "her", themAcc: "her" },
    he: { they: "he", them: "him", themAcc: "him" },
  },
  de: {
    // them = dative (erkläre IHR), themAcc = accusative (fordere SIE heraus)
    she: { they: "sie", them: "ihr", themAcc: "sie" },
    he: { they: "er", them: "ihm", themAcc: "ihn" },
  },
};

export function t(language, key, vars = {}) {
  const table = STRINGS[language] ?? STRINGS.en;
  const template = table[key] ?? STRINGS.en[key] ?? key;

  return template.replace(/\{(\w+)\}/g, (whole, name) =>
    name in vars ? String(vars[name]) : whole
  );
}

// The vars every session string needs, derived from the active character.
export function speakerVars(language, character) {
  const set =
    PRONOUNS[language]?.[character.subj] ?? PRONOUNS.en[character.subj];

  return {
    name: character.shortName,
    glyph: character.glyph,
    they: set.they,
    them: set.them,
    themAcc: set.themAcc,
  };
}
